#!/usr/bin/env python3
"""Normalize and register lecture source pairs.

A new lecture directory only needs one Quarto file and one notebook. This
script normalizes them to ``slides.qmd`` and ``learn.ipynb``, creates the
generated manifest when needed, and refreshes the lecture and schedule pages.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


SITE_ROOT = Path(__file__).resolve().parents[1]
LECTURES_DIR = SITE_ROOT / "lectures"
BEGIN_MARKER = "<!-- BEGIN AUTO-GENERATED LECTURES -->"
END_MARKER = "<!-- END AUTO-GENERATED LECTURES -->"


@dataclass(frozen=True)
class Lecture:
    slug: str
    number: str
    title: str
    slides: Path
    notebook: Path
    status: str


def _front_matter(source: str) -> dict[str, str]:
    lines = source.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    try:
        closing_index = next(
            index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"
        )
    except StopIteration:
        return {}

    values: dict[str, str] = {}
    for line in lines[1:closing_index]:
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*?)\s*$", line)
        if not match:
            continue
        key, value = match.groups()
        values[key] = value.strip("\"'")
    return values


def _qmd_metadata(path: Path) -> dict[str, str]:
    return _front_matter(path.read_text(encoding="utf-8"))


def _notebook_metadata(path: Path) -> dict[str, str]:
    notebook = json.loads(path.read_text(encoding="utf-8"))
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") == "markdown":
            return _front_matter("".join(cell.get("source", [])))
    return {}


def _lecture_number(slug: str) -> str:
    match = re.match(r"^([0-9]+[A-Za-z]?)", slug)
    return match.group(1) if match else slug


def _manifest_status(path: Path) -> str:
    if not path.exists():
        return "planned"
    match = re.search(r"^status:\s*([^\s#]+)", path.read_text(encoding="utf-8"), re.MULTILINE)
    return match.group(1) if match else "planned"


def _normalize_sources(directory: Path) -> tuple[Path, Path] | None:
    qmd_files = sorted(path for path in directory.glob("*.qmd") if path.is_file())
    notebook_files = sorted(path for path in directory.glob("*.ipynb") if path.is_file())
    slides = directory / "slides.qmd"
    notebook = directory / "learn.ipynb"

    if not qmd_files and not notebook_files:
        return None
    if not qmd_files or not notebook_files:
        raise RuntimeError(
            f"{directory.name} must contain one .qmd file and one .ipynb file"
        )

    if not slides.exists():
        if len(qmd_files) != 1:
            raise RuntimeError(
                f"{directory.name} has multiple .qmd files but no slides.qmd"
            )
        qmd_files[0].rename(slides)

    if not notebook.exists():
        manifest_exists = (directory / "manifest.yml").exists()
        if manifest_exists:
            legacy = directory / "notebook.ipynb"
            if legacy.exists():
                notebook = legacy
            else:
                raise RuntimeError(
                    f"{directory.name} has a manifest but no learn.ipynb or notebook.ipynb"
                )
        elif len(notebook_files) == 1:
            notebook_files[0].rename(notebook)
        else:
            raise RuntimeError(
                f"{directory.name} has multiple notebooks but no learn.ipynb"
            )

    return slides, notebook


def _write_manifest(lecture: Lecture) -> None:
    manifest = LECTURES_DIR / lecture.slug / "manifest.yml"
    if manifest.exists():
        return

    relative_notebook = lecture.notebook.relative_to(SITE_ROOT).as_posix()
    manifest.write_text(
        "\n".join(
            [
                "# Generated by scripts/sync_lectures.py.",
                f"title: {json.dumps(lecture.title)}",
                "status: planned",
                'owner: "course-staff"',
                'last_verified: ""',
                "verified_browsers: []",
                f"canonical_source: {relative_notebook}",
                "",
                "runtimes:",
                "  slides: revealjs-from-qmd",
                "  student_notebook: static-html",
                "  apps: []",
                "",
                "exports:",
                "  pdf: true",
                "  pptx: true",
                "  beamer: false",
                "",
            ]
        ),
        encoding="utf-8",
    )


def discover_lectures() -> list[Lecture]:
    lectures: list[Lecture] = []
    for directory in sorted(path for path in LECTURES_DIR.iterdir() if path.is_dir()):
        sources = _normalize_sources(directory)
        if sources is None:
            continue

        slides, notebook = sources
        metadata = _qmd_metadata(slides)
        if not metadata.get("title"):
            metadata.update(_notebook_metadata(notebook))
        title = metadata.get("title") or directory.name.replace("-", " ").title()
        lecture = Lecture(
            slug=directory.name,
            number=_lecture_number(directory.name),
            title=title,
            slides=slides,
            notebook=notebook,
            status=_manifest_status(directory / "manifest.yml"),
        )
        _write_manifest(lecture)
        lectures.append(lecture)

    return lectures


def _replace_generated_section(path: Path, body: str) -> None:
    source = path.read_text(encoding="utf-8")
    replacement = f"{BEGIN_MARKER}\n{body.rstrip()}\n{END_MARKER}"
    if BEGIN_MARKER not in source or END_MARKER not in source:
        raise RuntimeError(f"{path.relative_to(SITE_ROOT)} is missing generated-section markers")
    pattern = re.compile(
        rf"{re.escape(BEGIN_MARKER)}.*?{re.escape(END_MARKER)}",
        re.DOTALL,
    )
    path.write_text(pattern.sub(replacement, source), encoding="utf-8")


def _lecture_listing(lectures: list[Lecture]) -> str:
    entries = []
    for lecture in lectures:
        slides = lecture.slides.relative_to(SITE_ROOT).as_posix()
        notebook = lecture.notebook.relative_to(SITE_ROOT).as_posix()
        entries.append(
            f"- **{lecture.number} · {lecture.title}** — "
            f"[presentation deck]({slides}) · "
            f"[self-study notebook]({notebook})"
        )
    return "\n".join(entries)


def _schedule_table(lectures: list[Lecture]) -> str:
    rows = [
        "| # | Lecture | Status | Links |",
        "|---|---|---|---|",
    ]
    for lecture in lectures:
        slides = lecture.slides.relative_to(SITE_ROOT).as_posix()
        notebook = lecture.notebook.relative_to(SITE_ROOT).as_posix()
        rows.append(
            f"| {lecture.number} | {lecture.title} | {lecture.status} | "
            f"[slides]({slides}) · [notebook]({notebook}) |"
        )
    return "\n".join(rows)


def main() -> None:
    lectures = discover_lectures()
    _replace_generated_section(SITE_ROOT / "lectures.qmd", _lecture_listing(lectures))
    _replace_generated_section(SITE_ROOT / "schedule.qmd", _schedule_table(lectures))
    print(f"Synchronized {len(lectures)} lecture(s).")


if __name__ == "__main__":
    main()
