#!/usr/bin/env python3
"""Synchronize catalog metadata and refresh generated site pages."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import date
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import content_model
import colab
import gallery


MARKER_PREFIX = "<!-- BEGIN AUTO-GENERATED"
MARKER_SUFFIX = "-->"


@dataclass(frozen=True)
class GeneratedSection:
    name: str

    @property
    def begin(self) -> str:
        return f"{MARKER_PREFIX} {self.name} {MARKER_SUFFIX}"

    @property
    def end(self) -> str:
        return f"<!-- END AUTO-GENERATED {self.name} {MARKER_SUFFIX}"


LECTURES_SECTION = GeneratedSection("LECTURES")
SCHEDULE_SECTION = GeneratedSection("SCHEDULE")
ARCHIVE_SECTION = GeneratedSection("ARCHIVE")
ASSIGNMENTS_SECTION = GeneratedSection("ASSIGNMENTS")
TOOLS_SECTION = GeneratedSection("TOOLS")
OFFERING_BANNER_SECTION = GeneratedSection("OFFERING BANNER")
SYLLABUS_LOGISTICS_SECTION = GeneratedSection("SYLLABUS LOGISTICS")

EM_DASH = "—"


def _front_matter(source: str) -> dict[str, str]:
    lines = source.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    try:
        closing_index = next(
            index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"
        )
    except StopIteration:
        return {}

    values: dict[str, str] = {}
    for line in lines[1:closing_index]:
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*?)\s*$", line)
        if not match:
            continue
        key, value = match.groups()
        values[key] = value.strip("\"'")
    return values


def _qmd_metadata(path: Path) -> dict[str, str]:
    return _front_matter(path.read_text(encoding="utf-8"))


def _notebook_metadata(path: Path) -> dict[str, str]:
    notebook = json.loads(path.read_text(encoding="utf-8"))
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") == "markdown":
            return _front_matter("".join(cell.get("source", [])))
    return {}


def _lecture_number(slug: str) -> str:
    match = re.match(r"^([0-9]+[A-Za-z]?)", slug)
    return match.group(1) if match else slug


def _normalize_sources(directory: Path) -> tuple[Path, Path] | None:
    qmd_files = sorted(path for path in directory.glob("*.qmd") if path.is_file())
    notebook_files = sorted(path for path in directory.glob("*.ipynb") if path.is_file())
    slides = directory / "slides.qmd"
    notebook = directory / "learn.ipynb"

    if not qmd_files and not notebook_files:
        return None
    if not qmd_files or not notebook_files:
        raise RuntimeError(
            f"{directory.name} must contain one .qmd file and one .ipynb file"
        )

    if not slides.exists():
        if len(qmd_files) != 1:
            raise RuntimeError(
                f"{directory.name} has multiple .qmd files but no slides.qmd"
            )
        qmd_files[0].rename(slides)

    if not notebook.exists():
        manifest_exists = (directory / "manifest.yml").exists()
        if manifest_exists:
            legacy = directory / "notebook.ipynb"
            if legacy.exists():
                notebook = legacy
            else:
                raise RuntimeError(
                    f"{directory.name} has a manifest but no learn.ipynb or notebook.ipynb"
                )
        elif len(notebook_files) == 1:
            notebook_files[0].rename(notebook)
        else:
            raise RuntimeError(
                f"{directory.name} has multiple notebooks but no learn.ipynb"
            )

    return slides, notebook


def _write_manifest(directory: Path, *, title: str, notebook: Path) -> None:
    manifest = directory / "manifest.yml"
    if manifest.exists():
        return

    relative_notebook = notebook.relative_to(content_model.SITE_ROOT).as_posix()
    manifest.write_text(
        "\n".join(
            [
                "# Generated by scripts/sync_content.py.",
                f"title: {json.dumps(title)}",
                "status: planned",
                'owner: "course-staff"',
                'last_verified: ""',
                "verified_browsers: []",
                f"canonical_source: {relative_notebook}",
                "",
                "runtimes:",
                "  slides: revealjs-from-qmd",
                "  student_notebook: static-html",
                "  apps: []",
                "",
                "exports:",
                "  pdf: true",
                "  pptx: true",
                "  beamer: false",
                "",
            ]
        ),
        encoding="utf-8",
    )


def normalize_lecture_sources(lectures_dir: Path | None = None) -> int:
    lectures_dir = lectures_dir or content_model.LECTURES_DIR
    if not lectures_dir.is_dir():
        return 0

    normalized = 0
    for directory in sorted(path for path in lectures_dir.iterdir() if path.is_dir()):
        sources = _normalize_sources(directory)
        if sources is None:
            continue

        slides, notebook = sources
        metadata = _qmd_metadata(slides)
        if not metadata.get("title"):
            metadata.update(_notebook_metadata(notebook))
        title = metadata.get("title") or directory.name.replace("-", " ").title()
        _write_manifest(directory, title=title, notebook=notebook)
        normalized += 1
    return normalized


def replace_generated_section(
    path: Path,
    body: str,
    section: GeneratedSection,
) -> None:
    if not path.exists():
        raise RuntimeError(f"{path.relative_to(content_model.SITE_ROOT)} does not exist")

    source = path.read_text(encoding="utf-8")
    begin_count = source.count(section.begin)
    end_count = source.count(section.end)
    if begin_count != 1 or end_count != 1:
        raise RuntimeError(
            f"{path.relative_to(content_model.SITE_ROOT)} must contain exactly one "
            f"{section.name} generated-section marker pair "
            f"(found {begin_count} begin, {end_count} end)"
        )

    replacement = f"{section.begin}\n{body.rstrip()}\n{section.end}"
    pattern = re.compile(
        rf"{re.escape(section.begin)}.*?{re.escape(section.end)}",
        re.DOTALL,
    )
    path.write_text(pattern.sub(replacement, source), encoding="utf-8")


def escape_markdown_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _lecture_href(slug: str, surface: str) -> str:
    return f"{content_model.LECTURES_URL_PREFIX}/{slug}/{surface}"


def _lecture_app_href(slug: str, app_path: str) -> str:
    normalized = app_path.replace("\\", "/").strip("/")
    return f"{content_model.LECTURES_URL_PREFIX}/{slug}/{normalized}/"


def _format_lecture_apps(lecture: content_model.Lecture) -> str:
    if not lecture.apps:
        return ""
    links = [
        f"[{escape_markdown_table_cell(app.title)}]({_lecture_app_href(lecture.slug, app.path)})"
        for app in lecture.apps
    ]
    return " · apps: " + ", ".join(links)


def _assignment_href(slug: str, notebook: str) -> str:
    return f"{content_model.ASSIGNMENTS_URL_PREFIX}/{slug}/{notebook}"


def _repo_notebook_path(*parts: str) -> str:
    return "/".join(parts)


def _colab_badge(catalog: content_model.ContentCatalog, repo_relative_path: str) -> str:
    course = catalog.course
    return colab.badge_for_notebook(
        enabled=course.colab.enabled,
        owner=course.repo.owner,
        name=course.repo.name,
        branch=course.repo.branch,
        repo_relative_path=repo_relative_path,
    )


def _lecture_colab_badge(catalog: content_model.ContentCatalog, lecture: content_model.Lecture) -> str:
    path = _repo_notebook_path(
        content_model.LECTURES_URL_PREFIX,
        lecture.slug,
        lecture.surfaces.learn,
    )
    return _colab_badge(catalog, path)


def _assignment_colab_badge(
    catalog: content_model.ContentCatalog,
    assignment: content_model.Assignment,
) -> str:
    path = _repo_notebook_path(
        content_model.ASSIGNMENTS_URL_PREFIX,
        assignment.slug,
        assignment.notebook,
    )
    return _colab_badge(catalog, path)


def _append_colab_suffix(text: str, badge: str) -> str:
    if not badge:
        return text
    return f"{text} · {badge}"


def _assignment_due_map(
    catalog: content_model.ContentCatalog,
) -> dict[str, list[tuple[str, date | None]]]:
    schedule = content_model.current_offering_schedule(catalog)
    due: dict[str, list[tuple[str, date | None]]] = defaultdict(list)
    for row in schedule.rows:
        if row.assignment:
            due[row.assignment].append((row.week, row.date))
    return due


def _format_due_weeks(due_weeks: list[tuple[str, date | None]]) -> str:
    if not due_weeks:
        return EM_DASH

    formatted: list[str] = []
    for week, due_date in due_weeks:
        if due_date is None:
            formatted.append(f"Week {week}")
        else:
            formatted.append(f"Week {week} ({due_date.isoformat()})")
    return escape_markdown_table_cell("; ".join(formatted))


def _lecture_link(slug: str, surface: str, label: str) -> str:
    return f"[{escape_markdown_table_cell(label)}]({_lecture_href(slug, surface)})"


def _format_date(value: content_model.ScheduleRow) -> str:
    if value.date is None:
        return EM_DASH
    return value.date.isoformat()


def _schedule_table_rows(
    schedule: content_model.OfferingSchedule,
    lectures: dict[str, content_model.Lecture],
    *,
    catalog: content_model.ContentCatalog | None = None,
    assignments: dict[str, content_model.Assignment] | None = None,
) -> list[str]:
    rows = [
        "| Week | Date | Topic | Self-study | Slides | Assignment | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in schedule.rows:
        topic = escape_markdown_table_cell(row.topic) if row.topic else EM_DASH
        if row.lecture and row.lecture in lectures:
            lecture = lectures[row.lecture]
            learn_label = escape_markdown_table_cell(lecture.title)
            learn = _append_colab_suffix(
                _lecture_link(row.lecture, lecture.surfaces.learn, learn_label),
                _lecture_colab_badge(catalog, lecture) if catalog else "",
            )
        else:
            learn = EM_DASH
        if row.presentation and row.presentation in lectures:
            presentation_lecture = lectures[row.presentation]
            presentation = _lecture_link(
                row.presentation,
                presentation_lecture.surfaces.presentation,
                presentation_lecture.title,
            )
        else:
            presentation = EM_DASH
        if row.assignment and assignments and row.assignment in assignments:
            assignment = assignments[row.assignment]
            assignment_link = (
                f"[{escape_markdown_table_cell(assignment.title)}]"
                f"({_assignment_href(assignment.slug, assignment.notebook)})"
            )
            assignment_cell = _append_colab_suffix(
                assignment_link,
                _assignment_colab_badge(catalog, assignment) if catalog else "",
            )
        elif row.assignment:
            assignment_cell = escape_markdown_table_cell(row.assignment)
        else:
            assignment_cell = EM_DASH
        notes = escape_markdown_table_cell(row.notes) if row.notes else EM_DASH
        rows.append(
            "| "
            + " | ".join(
                [
                    escape_markdown_table_cell(row.week),
                    _format_date(row),
                    topic,
                    learn,
                    presentation,
                    assignment_cell,
                    notes,
                ]
            )
            + " |"
        )
    return rows


def render_schedule_page(catalog: content_model.ContentCatalog) -> str:
    if not catalog.offerings:
        return "_No offerings are configured yet._"

    schedule = content_model.current_offering_schedule(catalog)
    lectures = {lecture.slug: lecture for lecture in catalog.lectures}
    assignments = {assignment.slug: assignment for assignment in catalog.assignments}
    if not schedule.rows:
        return f"_The {schedule.offering.label} schedule has no weeks yet._"
    return "\n".join(
        _schedule_table_rows(
            schedule,
            lectures,
            catalog=catalog,
            assignments=assignments,
        )
    )


def _lectures_by_subject(lectures: tuple[content_model.Lecture, ...]) -> dict[str, list[content_model.Lecture]]:
    grouped: dict[str, list[content_model.Lecture]] = defaultdict(list)
    for lecture in lectures:
        if lecture.subjects:
            for subject in lecture.subjects:
                grouped[subject].append(lecture)
        else:
            grouped["Other topics"].append(lecture)

    for subject in grouped:
        grouped[subject].sort(key=content_model._lecture_sort_key)
    return dict(sorted(grouped.items(), key=lambda item: item[0].casefold()))


def render_lectures_page(catalog: content_model.ContentCatalog) -> str:
    if not catalog.lectures:
        return "_No lectures are published in the catalog yet._"

    sections: list[str] = []
    for subject, lectures in _lectures_by_subject(catalog.lectures).items():
        entries: list[str] = []
        for lecture in lectures:
            presentation = _lecture_href(lecture.slug, lecture.surfaces.presentation)
            notebook = _lecture_href(lecture.slug, lecture.surfaces.learn)
            title = escape_markdown_table_cell(f"{lecture.number} · {lecture.title}")
            colab_badge = _lecture_colab_badge(catalog, lecture)
            self_study = _append_colab_suffix(
                f"[self-study notebook]({notebook})",
                colab_badge,
            )
            apps = _format_lecture_apps(lecture)
            entries.append(
                f"- **{title}** — "
                f"[presentation deck]({presentation}) · "
                f"{self_study}{apps}"
            )
        sections.append(f"### {escape_markdown_table_cell(subject)}\n\n" + "\n".join(entries))
    return "\n\n".join(sections)


def _assignments_by_subject(
    assignments: tuple[content_model.Assignment, ...],
) -> dict[str, list[content_model.Assignment]]:
    grouped: dict[str, list[content_model.Assignment]] = defaultdict(list)
    for assignment in assignments:
        if assignment.subjects:
            for subject in assignment.subjects:
                grouped[subject].append(assignment)
        else:
            grouped["Other topics"].append(assignment)

    for subject in grouped:
        grouped[subject].sort(key=lambda item: (item.title.casefold(), item.slug))
    return dict(sorted(grouped.items(), key=lambda item: item[0].casefold()))


def _related_lecture_links(
    assignment: content_model.Assignment,
    lectures: dict[str, content_model.Lecture],
) -> str:
    if not assignment.related_lectures:
        return EM_DASH

    links: list[str] = []
    for slug in assignment.related_lectures:
        lecture = lectures.get(slug)
        if lecture is None:
            continue
        label = escape_markdown_table_cell(f"{lecture.number} · {lecture.title}")
        links.append(
            f"[{label}]({_lecture_href(slug, lecture.surfaces.learn)})"
        )
    return ", ".join(links) if links else EM_DASH


def render_assignments_page(catalog: content_model.ContentCatalog) -> str:
    if not catalog.assignments:
        return "_No assignments are published in the catalog yet._"

    lectures = {lecture.slug: lecture for lecture in catalog.lectures}
    due_map = _assignment_due_map(catalog)
    sections: list[str] = []
    for subject, assignments in _assignments_by_subject(catalog.assignments).items():
        entries: list[str] = []
        for assignment in assignments:
            title = escape_markdown_table_cell(assignment.title)
            notebook_link = (
                f"[notebook]({_assignment_href(assignment.slug, assignment.notebook)})"
            )
            colab_badge = _assignment_colab_badge(catalog, assignment)
            links = _append_colab_suffix(notebook_link, colab_badge)
            due = _format_due_weeks(due_map.get(assignment.slug, []))
            related = _related_lecture_links(assignment, lectures)
            estimated = (
                escape_markdown_table_cell(assignment.estimated_time)
                if assignment.estimated_time
                else EM_DASH
            )
            entries.append(
                f"- **{title}** — {links} · due {due} · "
                f"est. {estimated} · related lectures: {related}"
            )
        sections.append(f"### {escape_markdown_table_cell(subject)}\n\n" + "\n".join(entries))
    return "\n\n".join(sections)


def _tools_by_subject(
    entries: tuple[gallery.GalleryEntry, ...],
) -> dict[str, list[gallery.GalleryEntry]]:
    grouped: dict[str, list[gallery.GalleryEntry]] = defaultdict(list)
    for entry in entries:
        if entry.subjects:
            for subject in entry.subjects:
                grouped[subject].append(entry)
        else:
            grouped["Other topics"].append(entry)

    for subject in grouped:
        grouped[subject].sort(key=lambda item: (item.title.casefold(), item.id))
    return dict(sorted(grouped.items(), key=lambda item: item[0].casefold()))


def _tool_provenance(entry: gallery.GalleryEntry) -> str:
    if entry.source_kind == "standalone":
        return "standalone"
    if entry.source_lecture_number:
        return (
            f"from Lecture {escape_markdown_table_cell(entry.source_lecture_number)} · "
            f"{escape_markdown_table_cell(entry.source_title)}"
        )
    return f"from {escape_markdown_table_cell(entry.source_title)}"


def render_tools_page(entries: tuple[gallery.GalleryEntry, ...]) -> str:
    if not entries:
        return "_No interactive tools are published in the gallery yet._"

    sections: list[str] = []
    for subject, subject_entries in _tools_by_subject(entries).items():
        cards: list[str] = []
        for entry in subject_entries:
            title = escape_markdown_table_cell(entry.title)
            provenance = _tool_provenance(entry)
            summary = escape_markdown_table_cell(entry.summary) if entry.summary else ""
            summary_bit = f" — {summary}" if summary else ""
            cards.append(
                f"- **[{title}]({entry.href})** — {provenance}{summary_bit}"
            )
        sections.append(f"### {escape_markdown_table_cell(subject)}\n\n" + "\n".join(cards))
    return "\n\n".join(sections)


def render_archive_page(catalog: content_model.ContentCatalog) -> str:
    if not catalog.offerings:
        return "_No offerings are configured yet._"

    lectures = {lecture.slug: lecture for lecture in catalog.lectures}
    assignments = {assignment.slug: assignment for assignment in catalog.assignments}
    blocks: list[str] = []
    for offering_schedule in catalog.offerings:
        offering = offering_schedule.offering
        summary = html.escape(offering.label)
        if offering.start_date and offering.end_date:
            summary += (
                f" ({offering.start_date.isoformat()} – {offering.end_date.isoformat()})"
            )
        if offering_schedule.offering.term == catalog.course.current_offering:
            summary += " — current"

        if not offering_schedule.rows:
            body = f"_The {html.escape(offering.label)} schedule has no weeks yet._"
        else:
            body = "\n".join(
                _schedule_table_rows(
                    offering_schedule,
                    lectures,
                    catalog=catalog if offering_schedule.offering.term == catalog.course.current_offering else None,
                    assignments=assignments,
                )
            )

        blocks.append(
            "\n".join(
                [
                    "<details>",
                    f"<summary><strong>{summary}</strong></summary>",
                    "",
                    body,
                    "",
                    "</details>",
                ]
            )
        )
    return "\n\n".join(blocks)


def render_offering_banner(catalog: content_model.ContentCatalog) -> str:
    if not catalog.offerings:
        return "_Course offering details will appear here once configured._"

    schedule = content_model.current_offering_schedule(catalog)
    offering = schedule.offering
    lines = [f"**{escape_markdown_table_cell(offering.label)}**", ""]

    if offering.start_date and offering.end_date:
        lines.append(
            f"- **Dates:** {offering.start_date.isoformat()} – {offering.end_date.isoformat()}"
        )
    if offering.meeting.time or offering.meeting.place:
        meeting_parts = [part for part in (offering.meeting.time, offering.meeting.place) if part]
        lines.append(f"- **Meeting:** {' · '.join(meeting_parts)}")
    if catalog.course.instructors:
        instructor_bits: list[str] = []
        for instructor in catalog.course.instructors:
            if instructor.url:
                instructor_bits.append(
                    f"[{escape_markdown_table_cell(instructor.name)}]({instructor.url})"
                )
            else:
                instructor_bits.append(escape_markdown_table_cell(instructor.name))
        lines.append(f"- **Instructor(s):** {', '.join(instructor_bits)}")

    return "\n".join(lines)


def _render_person_entry(person: dict[str, object]) -> str | None:
    name = str(person.get("name") or "").strip()
    if not name:
        return None
    role = str(person.get("role") or "").strip()
    url = str(person.get("url") or "").strip()
    label = escape_markdown_table_cell(name)
    if url:
        label = f"[{label}]({url})"
    if role:
        return f"- {label} — {escape_markdown_table_cell(role)}"
    return f"- {label}"


def render_syllabus_logistics(catalog: content_model.ContentCatalog) -> str:
    if not catalog.offerings:
        return "_Current-term logistics will appear here once configured._"

    schedule = content_model.current_offering_schedule(catalog)
    offering = schedule.offering
    lines = [f"### {escape_markdown_table_cell(offering.label)}", ""]

    if offering.start_date and offering.end_date:
        lines.append(
            f"- **Dates:** {offering.start_date.isoformat()} – {offering.end_date.isoformat()}"
        )
    if offering.meeting.time or offering.meeting.place:
        meeting_parts = [part for part in (offering.meeting.time, offering.meeting.place) if part]
        lines.append(f"- **Meeting:** {' · '.join(meeting_parts)}")
    if catalog.course.instructors:
        instructor_bits: list[str] = []
        for instructor in catalog.course.instructors:
            if instructor.url:
                instructor_bits.append(
                    f"[{escape_markdown_table_cell(instructor.name)}]({instructor.url})"
                )
            else:
                instructor_bits.append(escape_markdown_table_cell(instructor.name))
        lines.append(f"- **Instructor(s):** {', '.join(instructor_bits)}")

    staff_entries = [
        entry for person in offering.staff if (entry := _render_person_entry(person)) is not None
    ]
    if staff_entries:
        lines.extend(["", "#### Staff", ""])
        lines.extend(staff_entries)

    announcement_lines: list[str] = []
    for announcement in offering.announcements:
        text = str(
            announcement.get("text") or announcement.get("message") or ""
        ).strip()
        if not text:
            continue
        date_raw = announcement.get("date")
        if date_raw:
            date_value = (
                date_raw.isoformat()
                if isinstance(date_raw, date)
                else str(date_raw).strip()
            )
        else:
            date_value = ""
        if date_value:
            announcement_lines.append(
                f"- **{escape_markdown_table_cell(date_value)}:** "
                f"{escape_markdown_table_cell(text)}"
            )
        else:
            announcement_lines.append(f"- {escape_markdown_table_cell(text)}")
    if announcement_lines:
        lines.extend(["", "#### Announcements", ""])
        lines.extend(announcement_lines)

    if offering.grading_notes:
        lines.extend(["", "#### Grading notes (this term)", ""])
        lines.append(offering.grading_notes)

    return "\n".join(lines)


def _relative_source_path(path: Path) -> str:
    return path.relative_to(content_model.SITE_ROOT).as_posix()


def _json_date(value: date | None) -> str | None:
    return value.isoformat() if value else None


def _json_metadata(value: object) -> object:
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, dict):
        return {str(key): _json_metadata(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_metadata(item) for item in value]
    return value


def catalog_to_dict(catalog: content_model.ContentCatalog) -> dict[str, object]:
    return {
        "course": {
            "title": catalog.course.title,
            "current_offering": catalog.course.current_offering,
            "repo": {
                "owner": catalog.course.repo.owner,
                "name": catalog.course.repo.name,
                "branch": catalog.course.repo.branch,
            },
            "colab": {"enabled": catalog.course.colab.enabled},
            "instructors": [
                {"name": instructor.name, "url": instructor.url}
                for instructor in catalog.course.instructors
            ],
            "source_path": _relative_source_path(catalog.course.source_path),
        },
        "lectures": [
            {
                "slug": lecture.slug,
                "number": lecture.number,
                "title": lecture.title,
                "subjects": list(lecture.subjects),
                "status": lecture.status,
                "surfaces": {
                    "learn": lecture.surfaces.learn,
                    "presentation": lecture.surfaces.presentation,
                },
                "apps": [
                    {
                        "id": app.id,
                        "title": app.title,
                        "path": app.path,
                        "runtime": app.runtime,
                        "gallery": app.gallery,
                    }
                    for app in lecture.apps
                ],
                "source_path": _relative_source_path(lecture.source_path),
            }
            for lecture in catalog.lectures
        ],
        "assignments": [
            {
                "slug": assignment.slug,
                "title": assignment.title,
                "subjects": list(assignment.subjects),
                "estimated_time": assignment.estimated_time,
                "notebook": assignment.notebook,
                "related_lectures": list(assignment.related_lectures),
                "status": assignment.status,
                "source_path": _relative_source_path(assignment.source_path),
            }
            for assignment in catalog.assignments
        ],
        "tools": [
            {
                "slug": tool.slug,
                "title": tool.title,
                "summary": tool.summary,
                "entrypoint": tool.entrypoint,
                "subjects": list(tool.subjects),
                "runtime": tool.runtime,
                "gallery": tool.gallery,
                "source_path": _relative_source_path(tool.source_path),
            }
            for tool in catalog.tools
        ],
        "offerings": [
            {
                "term": offering_schedule.offering.term,
                "label": offering_schedule.offering.label,
                "start_date": _json_date(offering_schedule.offering.start_date),
                "end_date": _json_date(offering_schedule.offering.end_date),
                "meeting": {
                    "time": offering_schedule.offering.meeting.time,
                    "place": offering_schedule.offering.meeting.place,
                },
                "staff": _json_metadata(list(offering_schedule.offering.staff)),
                "announcements": _json_metadata(list(offering_schedule.offering.announcements)),
                "grading_notes": offering_schedule.offering.grading_notes,
                "schedule": [
                    {
                        "week": row.week,
                        "date": _json_date(row.date),
                        "topic": row.topic,
                        "lecture": row.lecture,
                        "presentation": row.presentation,
                        "assignment": row.assignment,
                        "notes": row.notes,
                    }
                    for row in offering_schedule.rows
                ],
                "source_path": _relative_source_path(offering_schedule.source_path),
            }
            for offering_schedule in catalog.offerings
        ],
    }


def write_catalog_json(
    catalog: content_model.ContentCatalog,
    destination: Path | None = None,
) -> Path:
    destination = destination or content_model.SITE_ROOT / "generated" / "catalog.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = catalog_to_dict(catalog)
    serialized = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    destination.write_text(serialized, encoding="utf-8")
    return destination


def sync_catalog_pages(catalog: content_model.ContentCatalog | None = None) -> content_model.ContentCatalog:
    catalog = catalog or content_model.load_catalog()
    replace_generated_section(
        content_model.SITE_ROOT / "lectures.qmd",
        render_lectures_page(catalog),
        LECTURES_SECTION,
    )
    replace_generated_section(
        content_model.SITE_ROOT / "schedule.qmd",
        render_schedule_page(catalog),
        SCHEDULE_SECTION,
    )
    replace_generated_section(
        content_model.SITE_ROOT / "archive.qmd",
        render_archive_page(catalog),
        ARCHIVE_SECTION,
    )
    replace_generated_section(
        content_model.SITE_ROOT / "index.qmd",
        render_offering_banner(catalog),
        OFFERING_BANNER_SECTION,
    )
    syllabus_path = content_model.SITE_ROOT / "syllabus.qmd"
    if syllabus_path.exists():
        replace_generated_section(
            syllabus_path,
            render_syllabus_logistics(catalog),
            SYLLABUS_LOGISTICS_SECTION,
        )
    assignments_path = content_model.SITE_ROOT / "assignments.qmd"
    if assignments_path.exists():
        replace_generated_section(
            assignments_path,
            render_assignments_page(catalog),
            ASSIGNMENTS_SECTION,
        )
    write_catalog_json(catalog)
    return catalog


def sync_gallery_pages() -> None:
    gallery_path = content_model.SITE_ROOT / "generated" / "gallery.json"
    if not gallery_path.exists():
        raise RuntimeError(
            f"{gallery_path.relative_to(content_model.SITE_ROOT)} not found; "
            "run scripts/build_interactives.py first"
        )
    tools_path = content_model.SITE_ROOT / "tools.qmd"
    if not tools_path.exists():
        raise RuntimeError(
            f"{tools_path.relative_to(content_model.SITE_ROOT)} does not exist"
        )

    entries = gallery.load_gallery_json(gallery_path)
    replace_generated_section(
        tools_path,
        render_tools_page(entries),
        TOOLS_SECTION,
    )


def run_phase(phase: str) -> None:
    if phase == "catalog":
        normalized = normalize_lecture_sources()
        catalog = sync_catalog_pages()
        print(
            f"Synchronized catalog: {normalized} normalized lecture(s), "
            f"{len(catalog.lectures)} lecture(s), "
            f"{len(catalog.assignments)} assignment(s), "
            f"{len(catalog.offerings)} offering(s)."
        )
        return
    if phase == "gallery":
        sync_gallery_pages()
        entries = gallery.load_gallery_json()
        print(f"Gallery phase complete: {len(entries)} tool(s) published.")
        return
    raise SystemExit(f"unknown sync phase: {phase}")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--phase",
        choices=("catalog", "gallery"),
        default="catalog",
        help="sync phase to run (default: catalog)",
    )
    args = parser.parse_args(argv)
    run_phase(args.phase)


if __name__ == "__main__":
    main()
